apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-learn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cmarin96/argo-learn.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-learn

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
